### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by joerivanruth** [colinbate/ng2-brunch#3]
Hi Colin, I'm unable to run the example, it fails during compilation:

```
> ng2-brunch@0.3.0 build /Users/joeri/work/github/colinbate/ng2-brunch
> brunch build

05 Apr 07:23:18 - info: compiling
05 Apr 07:23:19 - error: Resolving deps of app/app.ts failed. Could not load module 'home' from '/Users/joeri/work/github/colinbate/ng2-brunch/app'. Possible solution: add 'home' to package.json and `npm install`. 
05 Apr 07:23:20 - info: compiled 475 files into 2 files, copied index.html in 6.1 sec

```

This is on an OSX system with node version v5.9.1 and npm 3.7.3

Attached detailed build output obtained with DEBUG='brunch:*' npm run build and the output of npm shrinkwrap for more version numbers. If you need more info please let me know.

[npm-shrinkwrap.json.txt](https://github.com/colinbate/ng2-brunch/files/203983/npm-shrinkwrap.json.txt)
[bruch-compile-failed.txt](https://github.com/colinbate/ng2-brunch/files/203973/bruch-compile-failed.txt)

Joeri

**Comment by colinbate** [comment]
Hi Joeri

This was caused by a bug in Brunch (https://github.com/brunch/brunch/issues/1275), the fix for which was published earlier today, probably not long after you tried this. The quickest way to fix it now should be to run `npm install deppack` to get the latest version of the Brunch dependency checker.

Let me know if that doesn't fix things.

**Comment by joerivanruth** [comment]
Great, it works now!

Thanks,

Joeri
