### ISSUE TITLE
styleUrls for components being added to global styles

### ISSUE THREAD

**Issue by rkaramc** [colinbate/ng2-brunch#6]
Hi,
Tried setting the styleUrls for the home component in the skeleton but the css is being joined into the global app.css file. Is there a way to stop this?

Thanks
Rajeev

**Comment by colinbate** [comment]
Yea, I initially just left the CSS alone so people could make their own choices around that, but it isn't in a great state out of the box, so I'm going to update it so that it is a bit more opinionated.

I'm not sure the stock `css-brunch` plugin will let you use `styleUrls` because it doesn't accept a pattern to tell which files to process. You can exclude the anything non-global with the `joinTo` in the config but Brunch will complain about them being compiled but not written. And if you want those files copied to the output folder (`public`) then you would probably need to put them in `app/assets` anyway.

My preference is to `require` the CSS files to inline them. I have a plugin for that. Then you can use `styles` instead of `styleUrls`. I'm about to update the skeleton to reflect this.

**Comment by colinbate** [comment]
I've updated the skeleton to use inline CSS by default.

But if you wanted to use `styleUrls` you can put the CSS files in the `assets` folder and they should copy over to somewhere you can reference them from a URL. Not ideal to separate them from the `.ts` files. In theory you could flag all `.component.css` files as assets (in the config), but there is a bug in Brunch which prevents this from working as expected. I've submitted a PR for it (https://github.com/brunch/brunch/pull/1407)

**Comment by colinbate** [comment]
Let me know if you are still having issues given the changes.

**Comment by rkaramc** [comment]
Looks good! Thanks Colin!
